
package ru.aksndr.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Greetings", targetNamespace = "http://server.aksndr.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Greetings {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCourse", targetNamespace = "http://server.aksndr.ru/", className = "ru.aksndr.client.GetCourse")
    @ResponseWrapper(localName = "getCourseResponse", targetNamespace = "http://server.aksndr.ru/", className = "ru.aksndr.client.GetCourseResponse")
    public String getCourse();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.aksndr.ru/", className = "ru.aksndr.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.aksndr.ru/", className = "ru.aksndr.client.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
